; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[env:denky32]
platform = espressif32
board = denky32
framework = arduino
monitor_speed = 115200
lib_deps =
	adafruit/Adafruit PWM Servo Driver Library@^3.0.3
